name: alquran
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  accordion: ^2.5.1
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter:
    sdk: flutter
  get: 4.6.5
  google_fonts: ^3.0.1
  lottie: ^1.4.2

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/json/
